# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8773bdb9290c7bb84e3e19022fad26b60d400317c6e672d32b57fe7701b2ccc33ea6423e27027760502a4181532d7f91c4f5cab71d5a8afd27dfc3276ab745e1

test:
  secret_key_base: 961a35db91fdd7489ae88c71cf6c453a7648c96dad612e7a8b18f7367efabe03834a46df722314d342f49633479c37fb5087eb3ff87a457537d38974a25bfc93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
